### ISSUE TITLE
How to buy software?

### ISSUE THREAD

**Issue by colesnicov** [raylibtech/rtools#12]
Good day.  Can you describe how your software is being purchased? Will I pay $20 and what's next?

**Comment by colesnicov** [comment]
I ask with reference to this  [**issue** ](https://github.com/raylibtech/rtools/issues/11)!

- Will I have access to the source code or send me a link to an executable file to download? 
- What if the downloaded binar can't start? 
- What if I buy a new computer, I have to pay another _$20_ ? 

**Thanks for the explanation.**

**Comment by raysan5** [comment]
Hi @colesnicov,

My tools are distributed through [itch.io](https://raylibtech.itch.io/), it's a software distribution platform specially well suited for independent developers like me. You need an itch.io account to buy any software.

 > Will I have access to the source code or send me a link to an executable file to download?

Most of those tools are not open source (only [rFXGen](https://github.com/raysan5/rfxgen)) and when you buy the tool on itch.io, you can download a .zip with the executable, a README.txt and depending on the tool some data file.

 > What if the downloaded binary can't start?

All my tools can be used online and also have a free version that can be downloaded to test if it works for you and fits your needs. The free version (ZERO) has some feature limitation and has no command-line. You can read about the limitations of version ZERO (free) vs ONE (paid) on itch.io. For most users the free version should be more than enough, the paid version is for advance users that require, for example, integrating the tool into some kind of pipeline.

 > What if I buy a new computer, I have to pay another $20 ?

Once you pay for a tool you can download that tool as many times as you want in any computer, there is no restriction.

What is your use case for the tool? Probably the free version is enough.

**Comment by colesnicov** [comment]
Hello. As I mentioned above, i can't start rGuiLayout on my Ubuntu machine and a web version of this software not works well on my monitor.. you can provide mi a binary what will works well?

**Comment by raysan5** [comment]
@colesnicov Sorry, I can't at this moment. I'll try to review the issue in the future.
