### ISSUE TITLE
[rGuiIcons] Generated C-Code seem outdated

### ISSUE THREAD

**Issue by furudbat** [raylibtech/rtools#13]
I'm made some custom icons with rGuiIcons ONE, but when I include the `ricons.h`-file, I getting this Error(s):

1.  `Error C2078 too many initializers    ricons.h:546`

Seems like the generated ricons uses a different guiIcons array size:  
_(custom) ricons.h:_
```C
static unsigned int guiIcons[RICON_MAX_ICONS] = {
```

_default icons (from `raygui.h`): _
```C
static unsigned int guiIcons[RICON_MAX_ICONS*RICON_DATA_ELEMENTS] = {
```

**Solution:**  
Use `RICON_MAX_ICONS*RICON_DATA_ELEMENTS` for the array size.

2.  `Error C2065 'RICON_MAX_NAME_LENGTH': undeclared identifier    raygui.h:3644`

**Solution:**  
Add `#define RICON_MAX_NAME_LENGTH  32`. 

**Environment:**
**OS:** Windows 10
**Compiler:** MSVC (2019)
**raylib Version:** 4.0-dev (from github)  
**raygui Version:** 3.0-dev (from github)  
**rGuiIcons ONE Version:** 1.0 (from itch.io)

My `raygui.c`:
```
#define RAYGUI_SUPPORT_RICONS
#define RAYGUI_SUPPORT_CUSTOM_RICONS
#define RAYGUI_IMPLEMENTATION
#include <raylib.h>
#include <raygui.h>
```

My Header:
```
#include <raylib.h>
#undef RAYGUI_IMPLEMENTATION
#define RAYGUI_SUPPORT_RICONS
#define RAYGUI_SUPPORT_CUSTOM_RICONS
#include <raygui.h>
```

**Comment by raysan5** [comment]
@furudbat thanks for reporting! `raygui` and `ricons` changed lately and I need to update the tools.

**Comment by raysan5** [comment]
@furudbat Updated source code, I'm planning a new release by the end of the month.
