### ISSUE TITLE
[rGuiLayout] ValueBox's text field can't be edited in rGuiLayout

### ISSUE THREAD

**Issue by Andidy** [raylibtech/rtools#15]
The label for ValueBox is exported by rGuiLayout. However, in rGuiLayout it cannot be edited. It would be nice if this was added since the text label goes outside of the part of the control visible in rGuiLayout and so proper layout cannot be accomplished if a text label for the ValueBox is desired.

Here's the layout in rGuiLayout, where the text in the ValueBox can't be edited:
![image](https://user-images.githubusercontent.com/37605997/138576089-51fbf08f-1d54-4efc-a212-f105cae10a9d.png)
Manually adding text to the ValueBox in the generated code then causes the control to be positioned poorly because
the text length can't be seen in rGuiLayout:
![image](https://user-images.githubusercontent.com/37605997/138576082-ad86639c-054f-484f-a846-5f9dc2d7c3d3.png)

**Comment by raysan5** [comment]
Reviewed.
