### ISSUE TITLE
[rGuiLayout] Coordinates get clipped if near edge of window

### ISSUE THREAD

**Issue by ryanford** [raylibtech/rtools#17]
As a QoL feature request - it would be nice if the coordinates moved above or below the placement area depending on it's relation to the edge of window.
![rayguilayout](https://user-images.githubusercontent.com/20901017/152635795-61908192-47b2-4a93-ae37-e36081efd3b6.gif)

**Comment by raysan5** [comment]
Issue reviewed in latest release of rGuiLayout. Also, the tool has been made open source.
