### ISSUE TITLE
Use scrollable container for High DPI mode in tools

### ISSUE THREAD

**Issue by ryanford** [raylibtech/rtools#18]
When switching to High DPI mode, some of the UI can be unreachable. As a feature request, if the UI could be nested inside a scrollable container it would be more usable
![image](https://user-images.githubusercontent.com/20901017/152674838-073aea8f-4092-40e7-ae56-c6bfc0a305b0.png)

**Comment by raysan5** [comment]
I'm afraid that feature is out-of-scope for this tools. HighDPI is intended for resolutions where it fits.
