### ISSUE TITLE
[rTexPacker] A specific .png file can not be loaded

### ISSUE THREAD

**Issue by AlienSteel** [raylibtech/rtools#19]
rTexPacker does not load the png files that i make myself in Krita, but works fine with a free tileset I tried with.

This file work:
![this works](https://user-images.githubusercontent.com/23486833/154815222-5ad1056f-b1f4-40b5-98b9-2f00ba8775c2.png)

This does not:
![does not work](https://user-images.githubusercontent.com/23486833/154815235-3619c8ba-e524-421c-b69e-053b03b7729c.png)

**Comment by raysan5** [comment]
It seems the PNG file contains several extra data chunks not supported by raylib PNG image loader library (stb_image). Here the PNG chunks of second image:

![image](https://user-images.githubusercontent.com/5766837/155005085-99355bc0-ef19-45c2-8b16-11b31fd28269.png)

It actually contains a very big text file with lot of exif metadata. I recommend you avoid that kind of metadata chunks when dealing with videogames assets. You should resave the PNG image with another software before importing it into rTexPacker, I recommend Paint.NET.
