### ISSUE TITLE
rGuiStyler offer custom styles with the downloaded program

### ISSUE THREAD

**Issue by Skytrias** [raylibtech/rtools#2]
This would be very nice to get different styles going much quicker without having to do it yourself, or just inspire the user to make a custom style himself more. 

Obviously more custom and awesome styles could be offered in the ONE version

**Comment by raysan5** [comment]
Already created some styles, available on [raygui repo](https://github.com/raysan5/raygui/tree/master/styles). They will be also availableto with new `rGuiStyler` release.

**Comment by raysan5** [comment]
@Skytrias Just published **[rGuiStyler 3.1](https://raylibtech.itch.io/rguistyler)** with sample styles included.
