### ISSUE TITLE
rQuizzer - response names all have an underscore appended

### ISSUE THREAD

**Issue by AndrewHamel111** [raylibtech/rtools#21]
This is occuring with the default quiz file, as well as modified ones. Only tested on Web. Also present for all styles.
![image](https://user-images.githubusercontent.com/46793311/158598633-5bc80105-b2b3-4912-aa02-5e3fee24aa91.png)

**Comment by raysan5** [comment]
By the way, the issue is related to text EOL between Windows and Linux.

**Comment by raysan5** [comment]
Solved, it will be ok in the next release.
