### ISSUE TITLE
[rGuiLayout] Missing `GuiSpinner()` text definitions on C code generation

### ISSUE THREAD

**Issue by paulob160a** [raylibtech/rtools#22]
Hi Ray, I have just started using your raylib libraries and examples. Pretty impressed. So I am sorry to be reporting some anomalous behaviour. Easy to fix but still a pain. Using rGuiLayout v2.5 I find that the definition of the text associated with a spinner is not written into the generated C' file. The code refers to this in the body but as it doesn't exist fails to compile. When I add the defines in by hand all is well.  I am working on Windows 10 v21H1 on an i5-8600K 32GB RAM. Building using Visual Studio 2022 v17..1.5. I have attached the gui file "gui_TestRgl00a.rgl" and the generated ".c" file I am using to create the page with. Am I being dense ? Great work, looking forward to using it more
[TestRgl00a.zip](https://github.com/raylibtech/rtools/files/8794024/TestRgl00a.zip)

**Comment by raysan5** [comment]
Hi Paul! Thanks for reporting! 

`raygui` has changed a bit lately and I'm planning a new release, I will also update `rGuiStyler`, `rGuiIcons` and `rGuiLayout` tools so I will review this issue.

I can't give you an ETA but I'll try to do it in the following 3 weeks.

**Comment by paulob160a** [comment]
Hi Ray,
            my pleasure! I look forward to the new release.

Thanks for taking the time to get back to me,

Paul

Paul O'Brien BSc (Hons)
________________________________

**Comment by raysan5** [comment]
@paulob160a Excuse the late response, this issue should be already fixed on latest `rGuiLayout` release. Also note that recently I open sourced all the `raygui` tools to avoid this kind of showstoppers, for anyone using those tools.

- **rGuiStyler**: https://github.com/raysan5/rguistyler
- **rGuiIcons**: https://github.com/raysan5/rguiicons
- **rGuilayout**: https://github.com/raysan5/rguilayout
