### ISSUE TITLE
[rTexPacker] Generates Corrupt .png on command line invocation

### ISSUE THREAD

**Issue by Huxellberger** [raylibtech/rtools#23]
Hi Ray,

I downloaded the standalone version to use as a build step for my custom engine. When using it as a gui it works well...however when invoking from the command line it seems to produce corrupt png files for both windows and linux. This is a bit of a nuisance as that is the exact use case I wanted it for. (trawling through files and auto generating atlases for me)

this is the log from my command if that's any assistance from a simple example setup. The rtpa file appears to have been generated correctly but the png is corrupted and cannot be opened. Possibly using a command wrong!

Cheers!
![image](https://user-images.githubusercontent.com/15147863/174926761-5a246646-69b9-4995-9854-ffa2ba5d8b65.png)

**Comment by raysan5** [comment]
@Huxellberger Thanks for reporting, could you send me the images you are packing to review them? You can send them to me: ray@raylibtech.com

**Comment by raysan5** [comment]
Issue reviewed and corrected.
