### ISSUE TITLE
[rTexPacker] textures are not using premultiplied alpha

### ISSUE THREAD

**Issue by Ahmaykmewsik** [raylibtech/rtools#24]
Packaged textures are not rendered using premultiplied alpha causing small distortions on some images. An example:

![image](https://user-images.githubusercontent.com/6686290/182213435-221f153d-8abe-4fb4-9568-29b4bdd3a97f.png)

(love this app & raylib! thanks so much Ray)

**Comment by raysan5** [comment]
@Ahmaykmewsik Excuse the late resonse, I'm just reviewing this issue.

**Comment by raysan5** [comment]
Fixed. A new release will be published (hopefully) next week.
