### ISSUE TITLE
[rGuiIcons] Convert Icons from 1.5 -> 2.1

### ISSUE THREAD

**Issue by furudbat** [raylibtech/rtools#26]
Hello,
I try to save/open my Icons from rGuiIcons v1.5 to v2.1.
But it seems like the Icons in 2.1 didn't get loaded.
(`guiIconName` seems to load but not `guiIcons` (data))

**Steps to Reproduce:**
1. create a new file in v1.5
2. edit it and save as .rgi
3. open the (v1.5) file in v2.1 

**rGuiIcons v1.5**
![image](https://user-images.githubusercontent.com/54323028/200202384-24e98108-7652-4673-aa42-19e3215d661e.png)

**rGuiIcons v2.1**
![image](https://user-images.githubusercontent.com/54323028/200202489-fb4353af-e1e5-4cdf-8d31-c3b48b2d4378.png)

**Environment:**
**OS: Linux**  
Full version of rGuiIcons

**Test File:**
[15.rgi.zip](https://github.com/raylibtech/rtools/files/9947127/15.rgi.zip)

**Comment by raysan5** [comment]
@furudbat I fixed this issue, it would be ok in next release, not sure when... But you can compile the tool yourself, it's open source: https://github.com/raysan5/rguiicons
