### ISSUE TITLE
[rGuiStyler] Support HighDPI and 4K monitors

### ISSUE THREAD

**Issue by Skytrias** [raylibtech/rtools#3]

**Comment by raysan5** [comment]
raylib supports HighDPI but there is some issue related: https://github.com/raysan5/raylib/issues/837

**Comment by gezzuzz** [comment]
i also find this a little frustrating..  on a 4k monitor the app is so small..  but i can move it to my 1080p monitor so i can deal with it.. a option that just scales everything up 2x would be nice..

**Comment by raysan5** [comment]
@gezzuzz I'll try to add the Screen x2 option for upcoming release.

**Comment by raysan5** [comment]
@gezzuzz Just published **[rGuiStyler 3.1](https://raylibtech.itch.io/rguistyler)**. Added a quick shortut to double screen size, Use `1` and `2` keys. I'll try to add a better mechanism (a button) in next version.
