### ISSUE TITLE
Windows 11 | App Scaling On High Resolution Displays

### ISSUE THREAD

**Issue by Gallocon** [raylibtech/rtools#30]
Hey hey! I've really enjoyed what I've seen for this app, but I figured I'd call out an issue I'm seeing.

**Windows 11 Version:** 22H2 (22621.1702)
**Display Resolution:** 3840 x 2400 px (16:10)
**Display Size (diagonal):** 15"
**OS scaling:** 250% (Recommended)

When I open the application, the frame of the app and text is locked to a small resolution, which seems to be ignoring the scaling of Windows. The app text is not legible at that size. 

Adjusting the High DPI settings via Properties >> Compatibility does not improve the viewing. On best case, the outcome for the view is the same. Though when using the High DPI Scale override for System or System (Enhanced) makes the app appear to open off-screen, and cannot be called to the viewable range via right-click menus or using Windows + Left or Right Arrow. 

The workaround is to manually change the display resolution at the system level to 1920x1200 and reducing scaling to 125% (which is recommended at that setting)

While it's impractical to have a display of this density on a laptop, a lot of devices nowadays are being produced like this.

If you have any questions about this, let me know!

**Comment by raysan5** [comment]
@Gallocon Thanks for reporting, I'm aware of this issue, actually High-DPI proper support is a raylib issue (and common in many graphics libraries). 

One solution I used on some tool is enabling a "screen x2" mode but I know that solution is not the best one; sometimes it content goes out of screen and it does not work with user resizable tools.

Also note that my tools use a pixel-perfect UI style, so, scaling them to non-integer sizes result in text blurring or other issues.

I neither have a High-DPI device to properly test and try to find a fix for the issue...

**Comment by raysan5** [comment]
@Gallocon In what application did you find this issue?

**Comment by Gallocon** [comment]
rFriendlyInstaller

**Comment by raysan5** [comment]
@Gallocon thanks, this issue is already reported and being addressed by https://github.com/raylibtech/rtools/issues/31 for next `rInstallFriendly 2.0` release. Closing this as a dup.
