### ISSUE TITLE
[rrespacker] Command-line interface not working

### ISSUE THREAD

**Issue by appybara13** [raylibtech/rtools#33]
This is with rrespacker 1.2 on linux.

```rrespacker --help``` launches the GUI rather than printing a help menu. 

This seems to also be true for the windows build, using wine.

**Comment by raysan5** [comment]
@appybara13 I'm aware of this issue and I'll try to upload an updated version as soon as possible.

**Comment by corentin35000** [comment]
@raysan5 Bonjour, j'ai acheter rrespacker mais le problème est toujours là pour la v1.2.0 je suis bloqué pour ma CLI dans ma CI/CD. A quand une mise à jour ? :/

**Comment by corentin35000** [comment]
Ne marche pas avec Linux et Windows, sachant que Linux dans ma CI/CD j'ai : 

debian@vps-4e8a304b:~/Crzgames_GameEngine/game-test-project/rrespacker/linux-x86_64$ ./rrespacker --help
rrespacker: external/glfw/src/monitor.c:451: glfwGetVideoMode: Assertion `monitor != NULL' failed.
Aborted

Windows : Ouvre l'application en mode GUI

@raysan5

**Comment by corentin35000** [comment]
Ou c'est nous pouvons avoir les sources pour pouvoir le recompiler ?

**Comment by raysan5** [comment]
Fixed.
