### ISSUE TITLE
[`rTexPacker`] Not opening on MacOS Sonoma M1

### ISSUE THREAD

**Issue by Ayehavgunne** [raylibtech/rtools#34]
I downloaded the MacOS zip file and unziped it but the resulting rtexpacker.app file cannot be opened. I get a MacOS popup that says "The application rtexpacker.app can't be opened"

I tried:
- right clicking in Finder and choosing 'Open' as sometimes downloaded programs from the internet require this
- viewing the contents of the rtexpacker.app and executing the rtexpacker.app/Contents/MacOS/rtexpacker file
- making rtexpacker.app executable with 'chmod +x'
- executing it from the command line

**Comment by raysan5** [comment]
@Ayehavgunne macOS support has been added quite recently and there seem to be still some issues to review...

**Comment by Ayehavgunne** [comment]
No problem. Just let me know if you need me to test anything!

Thanks!

**Comment by Ayehavgunne** [comment]
I downloaded rrespacker for Mac and it is working fine so far, FYI

**Comment by raysan5** [comment]
@Ayehavgunne thank you very much for the feedback, it was also updated recently and first time published for macOS.

**Comment by raysan5** [comment]
Issue reviewed on latest `rTexPacker 4.0` release: https://raylibtech.itch.io/rtexpacker
