### ISSUE TITLE
[`rInstallFriendly`] Not unpacking zip contents in Linux Mint

### ISSUE THREAD

**Issue by luis605** [raylibtech/rtools#35]
Hi,
I'm encountering an issue with rInstallerFriendly setup. I've configured it as follows:
![image](https://github.com/raylibtech/rtools/assets/60551627/15d68c13-ce39-4fa9-9924-0904247092e3)

However, the installer folder remains empty. Even when I attempt to save the contents in a root directory and run it as root, the folders are not being created and the installer tells me it unpacked 0MB:
![image](https://github.com/raylibtech/rtools/assets/60551627/fb278549-bba9-48f1-92b7-186f1ab12a76)

Additionally, the zip file is 200MB long.

When running the build installer on the CLI, I also get the following warnings:
```cpp
sudo ./"lit engine installer"
[sudo] password for lixt:       
ALSA lib pcm_dmix.c:1032:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm_dmix.c:1032:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm_dmix.c:1032:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm_dmix.c:1032:(snd_pcm_dmix_open) unable to open slave
```

This seems to be a Linux related issue, because this works on Windows.

**Comment by raysan5** [comment]
@luis605 Next release should fix this issue. Actually it's related to the way some .zip are packed: some packers consider directories as separate .zip entries while others do not and just add them to the file entries.

**Comment by luis605** [comment]
Amazing, looking forward to the next release!

**Comment by raysan5** [comment]
I'm closing the issue now because it should be already addressed... please, reopen if still failing after `rInstallFriendly 2.0` release.
