### ISSUE TITLE
[`rTexPacker`] Support for fixed glyphs width on font atlas generation

### ISSUE THREAD

**Issue by zapposh** [raylibtech/rtools#36]
Early 8 & 16 bit games usually had a fixed set of columns to display characters on.
The characters themselves all used the same "bounding box" size, for example 8x8 pixels, whether a letter, number or sign.

Many games created today still attempt to emulate this.
It is not only visually important, but prevents UI or HUD elements like the player score from erratically changing width and character positioning when the glyph width is not fixed. This is very noticeable in low-resolution games.

It would be great for rTexPacker to support fixed glyphs width on font atlas generation.

**Comment by raysan5** [comment]
@zapposh I'm adding this request to the features list.

**Comment by raysan5** [comment]
Issue reviewed on latest `rTexPacker 4.0` release: https://raylibtech.itch.io/rtexpacker
