### ISSUE TITLE
[`rTexPacker`] CLI: Use of directory as input source not working on Linux

### ISSUE THREAD

**Issue by scoobery** [raylibtech/rtools#38]
Here's some example output from what I'm seeing on my Linux machine when trying to run rTexPacker on a directory with a couple of PNGs in it.
**Command:** 
```
./rtexpacker -i ./model_sprites/dcss -o ./atlas.rtpa
```
**Output:**
```
Input sprite: ./model_sprites/dcss/./model_sprites/dcss/ElfBaseM.png
Input sprite: ./model_sprites/dcss/./model_sprites/dcss/ElfBaseF.png
```

This doesn't produce either an RTPA or PNG file as expected. But when I specify each individual PNG I want to pack (for example, `./rtexpacker -i ./model_sprites/dcss/ElfBaseF.png,./model_sprites/dcss/ElfBaseM.png -o ./atlas.rtpa`, that does end up creating an RTPA and PNG.

Let me know if you need any further details.

**Comment by raysan5** [comment]
@scoobery thanks for reporting, I will review it.

**Comment by raysan5** [comment]
Issue reviewed on latest `rTexPacker 4.0` release: https://raylibtech.itch.io/rtexpacker

**Comment by scoobery** [comment]
Looks to be working! Thank you so much!
