### ISSUE TITLE
[`rTexPacker`] Main window stops rendering when selecting a file

### ISSUE THREAD

**Issue by Rikaisan** [raylibtech/rtools#39]
Resizing the main window (either manually or automatically if you use a tiling window manager) while having the file explorer open to import a file (CTRL + O) will make the main window black until you open a file.

This issue is probably related to rendering being paused on the main thread until a file is chosen instead of it being a graphical issue, but I will leave the info just in case:

OS: EndeavourOS Linux x86_64
Kernel: 6.9.5-arch1-1
DE: Hyprland
GPU: RX6700XT
Video Driver: amdgpu

**Comment by raysan5** [comment]
@Rikaisan I'm afraid this is a limitation of the underlying windowing library, out of scope for this tool.
