### ISSUE TITLE
[rGuiStyler] Add option to set the background color

### ISSUE THREAD

**Issue by Skytrias** [raylibtech/rtools#4]
Each gui item only has 3 options for normal/focused/pressed which are border_color, base_color and text_color but where is the background for each of these? From the screenshots it looks like you can have different backgrounds

**Comment by raysan5** [comment]
Yes, `LINE_COLOR` and `BACKGROUND_COLOR` are extended properties of the *default* style, those properties are control-dependant, no simple way to expose them. Actually, for the current styles I setup those values manually directly on the **.rgs** text file.

**Comment by raysan5** [comment]
Added.
