### ISSUE TITLE
[`rTexViewer`] App softlocking if using a TWM and passthrough

### ISSUE THREAD

**Issue by Rikaisan** [raylibtech/rtools#40]
When using a tiling window manager, windows don't have server side decorations, therefore closing a window relies on a keybind or through a button/action inside the application; knowing this, this is how you can get softlocked:

1. Make changes to an image and don't save
2. Enable `window mouse pass-through`
3. Press `ESC` or try to close the app through a keybind
4. You will get a menu saying "Do you want to close without saving?" and be softlocked!

At this stage, you won't be able to interact with the menu or close the app in any way. You will be forced to kill the app by launching a terminal and killing it, losing all your progress.

This could be fixed by either making `ESC` toggle that menu (equivalent to pressing NO if the menu is open), disabling the `mouse pass-through` mode when a modal like that appears or both.

OS: EndeavourOS Linux x86_64
Kernel: 6.9.5-arch1-1
DE: Hyprland
GPU: RX6700XT
Video Driver: amdgpu

![image](https://github.com/raylibtech/rtools/assets/41881675/4f0bfe55-89c9-40c2-93d2-18c5afd13195)

**Comment by raysan5** [comment]
@Rikaisan Thanks for reporting, it will be reviewed for next release!

**Comment by raysan5** [comment]
Reviewed, should be ok on upcoming release.
