### ISSUE TITLE
[`rTexPacker`] Changing the order of sprites in the Sprite View

### ISSUE THREAD

**Issue by ChillyCider** [raylibtech/rtools#41]
My engine of choice, HaxeFlixel, accesses atlas frames by index instead of by name, so frame ordering is important in my case. I would love it if rTexPacker supported re-ordering or dragging around in the Sprite list, because then I could more easily put new sprites in the middle of the list.

**Comment by raysan5** [comment]
@ChillyCider Moving the sprites with drag is not trivial due to the limitations of the UI system but I will take a look, maybe I can support it with arrow keys at least

**Comment by ChillyCider** [comment]
> @ChillyCider Moving the sprites with drag is not trivial due to the limitations of the UI system but I will take a look, maybe I can support it with arrow keys at least

I'd accept arrow keys, no need to be fancy! :grin:

**Comment by raysan5** [comment]
Issue reviewed on latest rTexPacker 4.0 release: https://raylibtech.itch.io/rtexpacker
