### ISSUE TITLE
[`rTexPacker`] Show sprite index (in status bar?) when hovering over sprites in the Sprite list

### ISSUE THREAD

**Issue by ChillyCider** [raylibtech/rtools#42]
I find myself often having to hand-count the sprites in the atlas so I can determine their indexes. If this could be shown on hover, it would be a timesaver!

**Comment by raysan5** [comment]
@ChillyCider Do you mean the index position from the list? Starting at 0? That info can be added.

**Comment by ChillyCider** [comment]
Yep, starting from 0 or 1 if possible, preferably 0

**Comment by raysan5** [comment]
Issue reviewed on latest rTexPacker 4.0 release: https://raylibtech.itch.io/rtexpacker
