### ISSUE TITLE
[`rTexPacker`] On linux, make file dialogs reopen on the last directory

### ISSUE THREAD

**Issue by ChillyCider** [raylibtech/rtools#43]
Kinda like how other software tools do, just for productivity's sake.

As a customer, I'm mostly pleased with this tool, but I would love if you could make improvements on the 3 aspects I've added to the Issue Tracker today. It would really streamline my workflow! Thanks.

I am on Linux Mint, if it helps.

**Comment by raysan5** [comment]
@ChillyCider I think Windows already remember last opened directory, is it not that way on Linux? I think it can be reviewed.

**Comment by ChillyCider** [comment]
On my Linux Mint laptop, it opens in the home directory every time, very strange.
If any linux users could jump in and reproduce this, I would be grateful.

**Comment by raysan5** [comment]
Issue reviewed on latest `rTexPacker 4.0` release: https://raylibtech.itch.io/rtexpacker
