### ISSUE TITLE
[`rTexViewer`] Cannot select multiple files to open

### ISSUE THREAD

**Issue by acoto87** [raylibtech/rtools#45]
Hey, here's an issue I think could improve the experience on the app:

Cannot open multiple images/textures into tabs at once, need to open them one by one. 

I guess the directory mode functionality is a workaround, but that have other issues as well, particularly when you have asset folders with several images/textures.

Version of the tool

![image](https://github.com/user-attachments/assets/c3da0021-7e2e-44fe-b4ab-63268bfc69fe)

**Comment by raysan5** [comment]
@acoto87 What do you mean? When I drag and drop multiple images, they are open in multiple TABS in Tab-mode and also all are open in Board-mode.

**Comment by raysan5** [comment]
Reviewed, now multiple files can be selected on the load-file dialog.

**Comment by acoto87** [comment]
Yes, what I meant was to select multiple files from the open file dialog, not by drag-and-drop. Thanks!
