### ISSUE TITLE
[rTexViewer] Hovering semi-transparent pixels shows stuff from behind

### ISSUE THREAD

**Issue by acoto87** [raylibtech/rtools#46]
When loading textures with semi-transparent pixels and you hover them it shows stuff from behind the window app on the Image Info window.

![WhenHoveringSemiTransparentPixelsItShowsStuffFromDesktop](https://github.com/user-attachments/assets/61f8daa9-814e-4b79-b8c2-c9681cae448b)

System specifications
Processor	Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz   2.40 GHz
Installed RAM	12.0 GB (11.9 GB usable)
System type	64-bit operating system, x64-based processor

Windows specifications
Edition	Windows 10 Pro
Version	22H2
OS build	19045.4651

Tool version
![image](https://github.com/user-attachments/assets/9c569897-367e-451c-8533-126fa25e11b5)

**Comment by raysan5** [comment]
Reviewed, should be ok on upcoming release.
