### ISSUE TITLE
[`rTexViewer`] Open image from another directory while on directory mode

### ISSUE THREAD

**Issue by acoto87** [raylibtech/rtools#47]
Hey, here's an issue I think fixing it could improve the experience on the app:

Repro steps:
 1. Open the app
 2. Open a texture file and switch to directory mode. At this point you can browse through the textures in the directory using the < and > buttons on the bottom.
 3. Open a texture from another directory, it shows the texture.
 4. When using the < and > buttons on the bottom to change the current texture, you cannot go back to the texture you opened from another directory.

Version of the tool
![image](https://github.com/user-attachments/assets/16d75d21-561c-432e-9ac5-0b43054355a4)

**Comment by raysan5** [comment]
@acoto87 Actually that's the designed behaviour for directory mode, you can view the images from the directory you open the first image. What behaviour would you expect? In directory mode, the opened-image directory is the one processed.

**Comment by raysan5** [comment]
Current behaviour is the designed one.

**Comment by acoto87** [comment]
Maybe what is confusing to me, is the directory functionality. Since you can have multiple images opened from different directories, if you switch to directory mode it will show images images you don't explicitly opened, but only from the directory of the first image you opened. It's not quite clear what's hapenning. If you switch back again to other modes it would show the original images you opened. For me the directory mode serve the purpose of a slideshow through the images in a directory, more than to do actual work, for that is perfect.

This is a UX thing on the app, and if you know how the app behave it's fine, but I guess it can be improved.

If it helps, here are some tipical workflow I follow when using the app:

When opening the app, I find myself asking what I want to do, if I'm going to work on a directory of images, or a random collection of images from here and there. Based on the answer, I switch into the corresponding mode in the app and don't change it aftwards, and if later I want to open an unrelated image to the opened directory, or to open a different directory, I close everything and start over (or open another instance of the app). Another way I've done it, is to work with tabs/dashboard by opened images from the same directory, but never switch to the directory mode, because I'm working on a subset of the images and don't want to load every image on the directory and hit > (or < because I usually don't know the order of the images in the directory) to get to the one I care about.
