### ISSUE TITLE
[rTexPacker] GUI Overlap Conflicts

### ISSUE THREAD

**Issue by thismarvin** [raylibtech/rtools#6]
If a GUI element is covering another GUI element, and the user interacts on the topmost element, both GUI elements are affected.

For example, whenever the final "Export atlas file" GUI is prompted, if there is a sprite directly behind the "Ok" button, pressing on the button also selects said sprite. This ultimately results in the atlas image showing all sprites other than the sprite that was just selected with a gray tint.

**Comment by raysan5** [comment]
Hi @thismarvin! Thanks for reporting! I'll review this issue for the next version! :)

**Comment by raysan5** [comment]
reviewed.
