### ISSUE TITLE
[rTexViewer] Can't open any compressed images

### ISSUE THREAD

**Issue by kenchen3000** [raylibtech/rtools#7]
Hi,
I have RTexViewerOne, but it can't open any compressed images, such as DDS, KTX or ASTC. thanks.

**Comment by raysan5** [comment]
Hi @kenchen3000, this issue could be related to your GPU capabilities... does your GPU support those compressed formats? Keep in mind that GPU must support the compressed format, DDS should be supported by most desktop GPUs but KTX and ASTC could only be supported by modern GPUs.

Could you provide your GPU details? Could you provide some sample image for testing (you can attach them into a zip file to this issue)?

**Comment by raysan5** [comment]
No additional info provided, closing the issue.
