### ISSUE TITLE
[rTexPacker] Generate single PNG fonts for Raylib

### ISSUE THREAD

**Issue by edubart** [raylibtech/rtools#8]
I am trying to use rTexPacker to load fonts with Raylib using `LoadFontFromImage` function, but I always get crashes in that function. Is it possible to generate font atlases that are loadable by Raylib with rTexPacker? If yes then how? If no what other program could do it? In this use case I don't want to use TTFs.

**Comment by raysan5** [comment]
@edubart Actually, at this moment I think it's not possible with currently published `rTexPacker`, I was working in some modifications to allow that...

The problem with `LoadFontFromImage()` is that it requires a veryu specific structure of the PNG image to scan it properly (magenta background, same separation between characters, chars ordered in a rows and starting on SPACE...). Exactly like XNA SpriteFonts:

![62f6E](https://user-images.githubusercontent.com/5766837/89130306-1a891b80-d504-11ea-81c7-4a819dc0c455.png)

The best way to do that is loading the .PNG in `font.texture` and then manually load the exported `.xml/.json/.rtpa` text files characters information into `font.chars`.

**Comment by raysan5** [comment]
UPDATE: Generating this specific type of sprite fonts require more work than expected and I can't see much benefit on it from a professional point of view. For the moment it won't be added.
