### ISSUE TITLE
[rGuiLayout] Tool not usable on many laptops with max resolution 1366x768

### ISSUE THREAD

**Issue by zzador** [raylibtech/rtools#9]
The Window of the application is just too big for 2 of my laptops. Can't even see the window title bar. Must close the app from the taskbar. The easiest solution would be to enable Fullscreen mode I think but of course it would be much more elegant to include a layout-system (like Flexbox in CSS for example) in RayGUI to enable resolution independent layout design.

**Comment by raysan5** [comment]
@zzador A layout system is a big project, I'm afraid it's out-of-scope for raygui.

**Comment by zzador** [comment]
Well. I have allready implemented a BOX-Layout System for the GLFW Controls. Was all in all approx. a half day of work. I don't expect something like gridbag layout from java (which is horrible complex). I mean something like the super simple flexbox layout. This can be very easily realized. I might create a prototype for raygui myself over the weekend to demonstrate.
